# Generated by Django 5.0 on 2024-09-28 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobfairquizapp', '0002_question'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='question',
            new_name='QuizQuestion',
        ),
        migrations.AlterModelOptions(
            name='quiz',
            options={},
        ),
        migrations.AlterModelOptions(
            name='quizquestion',
            options={'verbose_name': 'Quiz Question', 'verbose_name_plural': 'Quiz Questions'},
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='marks',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='option_1',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='option_2',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='option_3',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='option_4',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='question',
        ),
        migrations.AlterModelTable(
            name='quiz',
            table=None,
        ),
    ]
