# Generated by Django 5.0 on 2024-09-28 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobfairquizapp', '0004_quizresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('clg_name', models.CharField(max_length=150)),
                ('phone_number', models.CharField(max_length=10, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserDetailsMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('total_marks', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'User Detail',
                'verbose_name_plural': 'User Details',
            },
        ),
        migrations.RemoveField(
            model_name='quizresult',
            name='quiz',
        ),
        migrations.RemoveField(
            model_name='quizresult',
            name='question',
        ),
        migrations.DeleteModel(
            name='Quiz',
        ),
        migrations.DeleteModel(
            name='QuizResult',
        ),
    ]
